apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-app-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao-cluster-store
    kind: ClusterSecretStore
  target:
    name: argo-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_MESSAGE
      remoteRef:
        key: poc/argo-app/prod
        property: message
