apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: poc

resources:
  - ../../base
  - externalsecret.yaml

labels:
  - pairs:
      poc.local/env: dev
      poc.local/managed-by: argocd
    includeSelectors: false
    includeTemplates: true

patches:
  - target:
      kind: Ingress
      name: argo-app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: argo-app-dev.local
  - target:
      kind: ConfigMap
      name: argo-app-config
    patch: |-
      - op: add
        path: /data/APP_ENV
        value: dev

images:
  - name: vlimanu/argocd-app
    newName: vlimanu/argocd-app
    newTag: sha-dde7134
